language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
env:
  - TEST_DIR=byte-tools
  - TEST_DIR=crypto-ops
  - TEST_DIR=crypto-tests
  - TEST_DIR=fake-simd
script: cd $TEST_DIR && cargo build --verbose && cargo test --verbose
