[workspace]
members = [
    "blobby",
    "block-buffer",
    "block-padding",
    "collectable",
    "cpufeatures",
    "dbl",
    "hex-literal",
    "inout",
    "opaque-debug",
    "wycheproof2blb",
    "zeroize",
    "zeroize/derive"
]
