[workspace]
members = [
    "block-buffer",
    "byte-tools",
    "crypto-tests",
    #"ctgrind",
    #"digest-buffer",
    "fake-simd",
]

[patch.crates-io]
block-cipher-trait = { git = "https://github.com/RustCrypto/traits" }
digest = { git = "https://github.com/RustCrypto/traits" }
