[workspace]
members = [
    "block-buffer",
    "byte-tools",
    "crypto-tests",
    #"ctgrind",
    #"digest-buffer",
    "fake-simd",
    "hex-literal",
    "hex-literal/hex-literal-impl",
    "opaque-debug",
]
