[package]
name = "block-buffer"
version = "0.3.1"
authors = ["The RustCrypto Devs"]
license = "MIT/Apache-2.0"
description = "Fixed size buffer for block processing of data"
documentation = "https://docs.rs/block-buffer"
repository = "https://github.com/RustCrypto/utils"
keywords = ["block", "padding", "pkcs7", "ansix923", "iso7816"]
categories = ["cryptography", "no-std"]

[dependencies]
arrayref = "0.3"
byte-tools = "0.2"
