[package]
name = "block-buffer"
version = "0.1.0"
authors = ["The RustCrypto Devs"]
license = "MIT/Apache-2.0"
description = "Fixed size buffer for block processing of input data"
documentation = "https://docs.rs/block-buffer"
repository = "https://github.com/RustCrypto/utils"
keywords = ["buffer", "digest"]

[dependencies]
generic-array = "0.7"
byte-tools = {path = "../byte-tools"}
