[package]
name = "block-buffer"
version = "0.5.1"
authors = ["RustCrypto Developers"]
license = "MIT/Apache-2.0"
description = "Fixed size buffer for block processing of data"
documentation = "https://docs.rs/block-buffer"
repository = "https://github.com/RustCrypto/utils"
keywords = ["block", "padding", "pkcs7", "ansix923", "iso7816"]
categories = ["cryptography", "no-std"]

[dependencies]
byte-tools = "0.2"
block-padding = "0.1"
generic-array = "0.11"
