[package]
name = "hex-literal"
version = "0.1.0"
authors = ["RustCrypto Developers"]
license = "MIT/Apache-2.0"
description = "Procedural macro for converting hexadecimal string to byte array at compile time."
documentation = "https://docs.rs/hex-literal"
repository = "https://github.com/RustCrypto/utils"
keywords = ["hex", "proc-macro", "literals"]

[dependencies]
proc-macro-hack = "0.4"
hex-literal-impl = { version = "0.1.0", path = "./hex-literal-impl" }
